### ISSUE TITLE
No Access Point

### ISSUE THREAD

**Issue by MicroBread** [mame82/P4wnP1#161]
After run ./install.sh, I reboot Pi0 but can't find Wi-Fi P4wnP1 so I can't use ssh to reconnect it.
In win10 it's recognized as "P4wnP1 by mame82" and in OSX there is a window shows "Keyboard Setup Assistant".

I install it and reboot:
1.sudo git clone --recursive https://github.com/mame82/P4wnP1
2.cd P4wnP1
3.sudo bash install.sh
4.sudo reboot

Am I do something wrong?

**Comment by HitItAll** [comment]
Do you have the RasPi0 W? You might have bought the cheaper one with no WiFi

**Comment by MicroBread** [comment]
@HitItAll sorry I can't reply you by e-mail. I'm sure it's a Pi0 W

**Comment by Swiftb0y** [comment]
Make sure you are using a Pi W and enable the Wifi access point in the setup.cfg as well as in the selected payload.

**Comment by MicroBread** [comment]
Thanks for your reply. I didn't change setup.cfg and it seems that
ACCESSPOINT open by default. As for payload I choose
hid_backdoor_remote.txt, something wrong?


2017-11-07 21:23 GMT+08:00 Swiftb0y <notifications@github.com>:

**Comment by Swiftb0y** [comment]
The hid_backdoor_remote.txt is The HID_backdoor which requires Internet.
This will enable the wifi client option and autoSSH which are both not configured. 
You need to use the plain hid_backdoor.txt 

The thing with the wifi client that it should fall back into Mastermode if it doesn't find the specified Network, which it doesn't do in your case. So try switching to the normal hid_remote and post the output `sudo journalctl -u P4wnP1.service` if your issue is not resolved by switching the payload.

**Comment by mame82** [comment]
Closed, no user feedback.
If issue is still present try the ready-to-go image provided here https://github.com/mame82/P4wnP1/releases
