### ISSUE TITLE
Hid backdoor remote issue

### ISSUE THREAD

**Issue by 99bit** [mame82/P4wnP1#179]
I don't know how to setup hid backdoor remote how to do so pls explain it!!.

**Comment by Swiftb0y** [comment]
I haven't played around with it much but it uses AutoSSH for the reverse ssh tunnel. Even though this is a bad example because I wasn't able to write the setup yet, you could always search for answers in the [wiki](http://p4wnp1.readthedocs.io/en/latest/P4wnP1-W/AutoSSH/)
I think the setup of the hid_backdoor_remote is the same as with any other AutoSSH scenario. So just "Google it".

**Comment by 99bit** [comment]
Any example of autos ssh host website ???

**Comment by mame82** [comment]
No an issue
