### ISSUE TITLE
Add simple webbinterface for controling pi zero w over mobile

### ISSUE THREAD

**Issue by jonas18z** [mame82/P4wnP1#37]
This is a future wish... 

Add some simple webinterface to control the pi zero w over a phone insteed of terminal/SSH?

**Comment by mame82** [comment]
@jonas18z Thanks for your request,

this idea makes sense for payloads which run longterm attacks. Or it would maybe make sense to design a payload, allowing to do the basic setup from a web interface (only on Pi Zero W, if not connected in device mode).

If you have the backdoor payload in mind, SSH won't be replaced for the following reasons:
- flexibility (one could dettach the backdoor server screen and get a shell to the raspbian instantly)
- extensibility: SSH allows to tunnel TCP sockets. As soon as the HID channel got socket tunneling implemented, this could be used to relax SSH based sockets through the target (pivoting)
- usability: beside nice things, like auto completion  a console allows all the things I haven't got in mind during development, while a webinterface only allows to do the things the developer had in mind
- a web interface runs in "request & response" style, due to the nature of HTTP. Getting output of remote processes to the screen (which is more push like) would become hard. On a web interface this means polling or choosing more complex techniques (f.e. AJAX)

Additionally, the backdoor shell could be bound to a PTY an made available via bluetooth serial connection

So there are a few reasons not to change the backdoor servers interface.

I leave it up to the community to develop payloads with web frontend.
