### ISSUE TITLE
Win10_Lockpicker takes forever

### ISSUE THREAD

**Issue by Anonyvius** [mame82/P4wnP1#60]
I dont know why. But the Win10 Lockpicker does not work i plugged the raspberry with the payload in my PC. Now i am waitung since 1 hour and nothing happens. The LED flashes two times. That meas it is waiting for the hash but nothing is happining.

**Comment by mame82** [comment]
That should be the normal behavior. Anyway, for me it worked on every testcase.
Unfortunately I'm not allowed to give any details on this (and thus I'm not able to tear down the problem).

I recommend reading the comments in the `Win10_LockPicker` payload file, perhaps they could point you in the right direction.

**Comment by amohacker** [comment]
My laptop just blocks the connection with the message isa policy has been changed and on my desktop a window pops up in my browser saying log in to proxy authtome:3128

**Comment by mame82** [comment]
@amohacker 
This is because HTTP is redirected to a non existing proxy server by Responder, which asks for authentication. Grabing hashes through manual HTTP access isn't in scope of the payload.

It's meant to be used on locked machines with a user logged in.

As stated, I'm not able to give more details, right now.
