### ISSUE TITLE
Not an issue but wondering

### ISSUE THREAD

**Issue by bytedeez** [mame82/P4wnP1#9]
Not an issue but i was going through the code and was trying to figure out where the setup for the 20Gb rdnis ether is. care to share?

**Comment by mame82** [comment]
The patch is in a separate repo (see links in P4wnP1 master branch readme) and will be merged into P4wnP1 on next release. 
There's no code, as it is a binary patch created by reversing usb_f_rndis.ko. I've done it that way, because otherwise P4wnP1 users would be forced to recompile Kernel modules. Want to keep things simple ;-)
